"""Agent type definitions: tasks, results, plans, and handoff messages."""

from __future__ import annotations

from typing import Any
from enum import Enum
from pydantic import BaseModel, Field


class AgentStatus(str, Enum):
    IDLE = "idle"
    THINKING = "thinking"
    PLANNING = "planning"
    RETRIEVING = "retrieving"
    CALLING = "calling"
    REASONING = "reasoning"
    COMPLETED = "completed"
    FAILED = "failed"


class AgentTask(BaseModel):
    """A unit of work to be executed by an agent."""
    task_id: str
    agent_id: str
    action: str
    params: dict[str, Any] = Field(default_factory=dict)
    user_id: str | None = None
    context: dict[str, Any] = Field(default_factory=dict)
    depends_on: list[str] = Field(default_factory=list)
    timeout_seconds: float = 30.0


class AgentResult(BaseModel):
    """Result of an agent's execution."""
    task_id: str
    agent_id: str
    action: str
    success: bool = True
    data: dict[str, Any] = Field(default_factory=dict)
    error: str | None = None
    latency_ms: float = 0
    confidence: float = 0.95
    tokens_used: int = 0
    tool_calls: int = 0
    sources: list[str] = Field(default_factory=list)


class ExecutionStep(BaseModel):
    """A single step in an execution plan."""
    step_id: str
    agent: str
    action: str
    params: dict[str, Any] = Field(default_factory=dict)
    depends_on: list[int] = Field(default_factory=list)
    status: str = "pending"


class ExecutionPlan(BaseModel):
    """Structured execution plan generated by the Planner."""
    workflow_id: str
    query: str
    intents: list[str] = Field(default_factory=list)
    steps: list[ExecutionStep] = Field(default_factory=list)
    estimated_latency_ms: float = 0


class HandoffMessage(BaseModel):
    """Message passed between agents during handoff."""
    from_agent: str
    to_agent: str
    action: str
    payload: dict[str, Any] = Field(default_factory=dict)
    context: dict[str, Any] = Field(default_factory=dict)


class VerificationResult(BaseModel):
    """Result of verifying an agent's output."""
    is_valid: bool = True
    confidence: float = 0.95
    issues: list[str] = Field(default_factory=list)
    suggestions: list[str] = Field(default_factory=list)
